apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: {{ .Values.name }}-model-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: {{ .Values.name }}-model-server
  name: {{ .Values.name }}-model-server
spec:
  ports:
  - port: {{ .Values.modelServicePort }}
    protocol: TCP
    targetPort: {{ .Values.modelServicePort }}
  selector:
    app.kubernetes.io/instance: {{ .Values.name }}-model-server
