name: Release Helm Chart Package

on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - path: charts/ai-software-templates/chatbot
            package: chatbot-ai-software-template
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: 3.12.1

      - name: Generate Helm Package
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          CHART_PATH=${{matrix.chart.path}}
          helm package $CHART_PATH
          echo "RELEASE_VERSION=${RELEASE_VERSION//v}" >> $GITHUB_ENV

      - name: Add packages to Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          draft: false
          files: ${{matrix.chart.package}}-${{env.RELEASE_VERSION}}.tgz
